meson:	meson.c.o
	$(CC) $(CPPFLAGS) $(CFLAGS) meson.c.o -o meson

meson.exe:	meson.c.o
	$(CC) $(CPPFLAGS) $(CFLAGS) meson.c.o -o meson.exe

meson.c.o: meson.c
	$(CC) $(LDFLAGS) -c meson.c -o meson.c.o
